error:
  whitelabel:
    enabled: false

amazon:
  associate_id: habuma-20

logging:
  level:
    root: DEBUG
#    org.hibernate: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.56.1:3306/springbootdb?useUnicode=true&characterEncoding=utf8
    username: root
    password: asdf
  jpa:
    properties:
      hinbernate:
        :dialect: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: create-drop